import { chromium } from '../../desktop/node_modules/playwright/index.mjs';
import { launchUnlocked } from './launch.mjs';
const BASE = process.env.SPJ_WEB_URL || 'http://localhost:4173/';
let pass = 0, fail = 0;
const check = (n, ok, d = '') => { (ok ? pass++ : fail++); console.log(`${ok ? 'PASS' : 'FAIL'}  ${n}${ok ? '' : ' — ' + d}`); };
const browser = await launchUnlocked(chromium);
const page = await (await browser.newContext({ viewport: { width: 390, height: 844 } })).newPage();
await page.goto(BASE);
await page.waitForSelector('[data-testid=home-page]');
// two categories with photos (and one entry without a photo)
await page.evaluate(async () => {
  const db = await new Promise((res, rej) => { const r = indexedDB.open('spj-photos', 1); r.onupgradeneeded = () => r.result.createObjectStore('photos'); r.onsuccess = () => res(r.result); r.onerror = () => rej(r.error); });
  const c = document.createElement('canvas'); c.width = 60; c.height = 60; c.getContext('2d').fillRect(0, 0, 60, 60);
  const blob = await new Promise((r) => c.toBlob(r, 'image/jpeg'));
  await new Promise((res) => { const t = db.transaction('photos', 'readwrite'); ['p1', 'p2', 'p3'].forEach((id) => t.objectStore('photos').put(blob, id)); t.oncomplete = res; });
  const mk = (id, metal, item, weight, photoId) => ({ id, date: '2026-10-01', type: 'in', metal, item, tunch: 92, weight, pcs: 1, note: '', photoId, createdAt: '2026-10-01T10:00:00Z' });
  localStorage.setItem('spj.stock.v1', JSON.stringify([mk('a', 'gold', 'Gold Ring – Classic', 5.5, 'p1'), mk('b', 'gold', 'Gold Ring – Classic', 6, 'p2'), mk('c', 'silver', 'Silver Anklet – Traditional', 38.5, 'p3'), mk('d', 'gold', 'Gold Chain – Daily Wear', 12.8)]));
});
await page.reload();
await page.waitForSelector('[data-testid=home-page]');
await page.click('[data-testid=open-gallery]');
await page.waitForSelector('[data-testid=gallery-page]');
check('opens on Gold with the gold look, a top switch Silver | Gold, and only gold photos (item + weight only)', (await page.getAttribute('[data-testid=gallery-page]', 'data-theme')) === 'gold' && (await page.locator('[data-testid=gallery-switch] button').allInnerTexts()).join('|') === 'Silver|Gold' && (await page.locator('[data-testid=gallery-photo]').count()) === 2 && (await page.locator('[data-testid=gallery-photo]').first().innerText()).replace(/\s+/g, ' ').trim() === 'Gold Ring – Classic 5.500 g');
check('bottom bar: All plus the gold categories', (await page.locator('[data-testid=gallery-cat-all]').count()) === 1 && (await page.locator('[data-testid=gallery-cat]').count()) === 1);
await page.click('[data-testid=gallery-silver]');
check('Silver switch: silver look, only the silver photo, silver categories below', (await page.getAttribute('[data-testid=gallery-page]', 'data-theme')) === 'silver' && (await page.locator('[data-testid=gallery-photo]').count()) === 1 && (await page.locator('[data-testid=gallery-cat]').filter({ hasText: 'Silver Anklet' }).count()) === 1);
await page.click('[data-testid=gallery-gold]');
await page.locator('[data-testid=gallery-cat]').filter({ hasText: 'Gold Ring' }).click();
check('a category button shows only its items', (await page.locator('[data-testid=gallery-photo]').count()) === 2);
await page.click('[data-testid=gallery-cat-all]');
await page.locator('[data-testid=gallery-photo]').first().click();
check('tapping a photo opens it large', await page.locator('[data-testid=gallery-viewer]').isVisible());
await page.locator('[data-testid=gallery-viewer]').click();
check('no lock while inside the Gallery', (await page.locator('[data-testid=app-lock]').count()) === 0);
await page.click('[data-testid=gallery-back]');
await page.waitForSelector('[data-testid=app-lock]');
check('coming back from the Gallery shows the blurred lock asking for the password', /blur/.test(await page.evaluate(() => getComputedStyle(document.querySelector('[data-testid=app-lock]')).backdropFilter || getComputedStyle(document.querySelector('[data-testid=app-lock]')).webkitBackdropFilter)));
await page.fill('[data-testid=lock-pass]', 'wrong'); await page.click('[data-testid=lock-submit]');
check('a wrong password keeps it locked', await page.locator('[data-testid=lock-error]').isVisible());
await page.fill('[data-testid=lock-pass]', '443262'); await page.click('[data-testid=lock-submit]');
await page.waitForSelector('[data-testid=app-lock]', { state: 'detached' });
check('the right password unlocks the app (Home)', await page.locator('[data-testid=home-page]').isVisible());
await browser.close();
console.log(`${pass}/${pass + fail} passed`);
process.exit(fail ? 1 : 0);
