import { chromium } from '../../desktop/node_modules/playwright/index.mjs';
import { launchUnlocked } from './launch.mjs';
const BASE = process.env.SPJ_WEB_URL || 'http://localhost:4173/';
let pass = 0, fail = 0;
const check = (n, ok, d = '') => { (ok ? pass++ : fail++); console.log(`${ok ? 'PASS' : 'FAIL'}  ${n}${ok ? '' : ' — ' + d}`); };
const browser = await launchUnlocked(chromium);
const page = await (await browser.newContext({ viewport: { width: 390, height: 844 } })).newPage();
await page.goto(BASE);
await page.waitForSelector('[data-testid=home-page]');
// photos in two categories: gold ring a (today, in stock), gold ring b (old, already sold), silver anklet c; d has no photo
await page.evaluate(async () => {
  const db = await new Promise((res, rej) => { const r = indexedDB.open('spj-photos', 1); r.onupgradeneeded = () => r.result.createObjectStore('photos'); r.onsuccess = () => res(r.result); r.onerror = () => rej(r.error); });
  const c = document.createElement('canvas'); c.width = 60; c.height = 60; c.getContext('2d').fillRect(0, 0, 60, 60);
  const blob = await new Promise((r) => c.toBlob(r, 'image/jpeg'));
  await new Promise((res) => { const t = db.transaction('photos', 'readwrite'); ['p1', 'p2', 'p3'].forEach((id) => t.objectStore('photos').put(blob, id)); t.oncomplete = res; });
  const p = (n) => String(n).padStart(2, '0'); const d = new Date(); const now = `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
  const mk = (id, type, metal, item, weight, photoId, date) => ({ id, date, type, metal, item, tunch: 92, weight, pcs: 1, note: '', photoId, createdAt: `${date}T10:00:00Z` });
  localStorage.setItem('spj.stock.v1', JSON.stringify([mk('a', 'in', 'gold', 'Gold Ring – Classic', 5.5, 'p1', now), mk('b', 'in', 'gold', 'Gold Ring – Classic', 6, 'p2', '2020-01-01'), mk('bo', 'out', 'gold', 'Gold Ring – Classic', 6, undefined, now), mk('c', 'in', 'silver', 'Silver Anklet – Traditional', 38.5, 'p3', now), mk('d', 'in', 'gold', 'Gold Chain – Daily Wear', 12.8, undefined, now)]));
});
await page.reload();
await page.waitForSelector('[data-testid=home-page]');
await page.click('[data-testid=open-gallery]');
await page.waitForSelector('[data-testid=gallery-page]');
const n = () => page.locator('[data-testid=gallery-photo]').count();
check('opens on Gold, gold look, top switch Silver | Gold, All shows the gold photos with only item + weight', (await page.getAttribute('[data-testid=gallery-page]', 'data-theme')) === 'gold' && (await page.locator('[data-testid=gallery-switch] button').allInnerTexts()).join('|') === 'Silver|Gold' && (await n()) === 2 && (await page.locator('[data-testid=gallery-photo]').first().innerText()).replace(/\s+/g, ' ').trim() === 'Gold Ring – Classic 5.500 g');
check('bottom bar: All | Albums | New | In stock | Sold', (await page.locator('[data-testid=gallery-nav] button').allInnerTexts()).join('|') === 'All|Albums|New|In stock|Sold');
await page.click('[data-testid=gallery-tab-new]'); check('New: only the piece added lately', (await n()) === 1);
await page.click('[data-testid=gallery-tab-stock]'); check('In stock: only the piece still in the shop', (await n()) === 1 && (await page.locator('[data-testid=gallery-photo]').innerText()).includes('5.500'));
await page.click('[data-testid=gallery-tab-sold]'); check('Sold: only the piece that has gone out', (await n()) === 1 && (await page.locator('[data-testid=gallery-photo]').innerText()).includes('6.000'));
await page.click('[data-testid=gallery-tab-albums]');
check('Albums: one album per category with its photo count', (await page.locator('[data-testid=gallery-album]').count()) === 1 && (await page.locator('[data-testid=gallery-album] .gx-count').innerText()) === '2');
await page.locator('[data-testid=gallery-album]').click();
check('opening an album shows its photos and a way back to Albums', (await n()) === 2 && (await page.locator('[data-testid=gallery-albums-back]').count()) === 1);
await page.click('[data-testid=gallery-albums-back]');
check('back to the albums list', (await page.locator('[data-testid=gallery-album]').count()) === 1);
await page.click('[data-testid=gallery-silver]');
check('Silver switch: silver look and only the silver photo / albums', (await page.getAttribute('[data-testid=gallery-page]', 'data-theme')) === 'silver' && (await page.locator('[data-testid=gallery-album]').count()) === 1 && (await page.locator('[data-testid=gallery-album]').innerText()).includes('Silver Anklet'));
await page.click('[data-testid=gallery-gold]');
await page.click('[data-testid=gallery-tab-all]');
await page.locator('[data-testid=gallery-photo]').first().click();
check('tapping a photo opens it on its own page (big, with its item and weight)', await page.locator('[data-testid=gallery-viewer]').isVisible() && (await page.locator('[data-testid=gallery-viewer] .gx-caption').innerText()).replace(/\s+/g, ' ').includes('5.500 g'));
await page.click('[data-testid=gallery-next]');
check('next shows the following piece', (await page.locator('[data-testid=gallery-viewer] .gx-caption').innerText()).replace(/\s+/g, ' ').includes('6.000 g'));
await page.click('[data-testid=gallery-viewer-back]');
await page.waitForSelector('[data-testid=gallery-viewer]', { state: 'detached' });
check('no lock while inside the Gallery', (await page.locator('[data-testid=app-lock]').count()) === 0);
await page.click('[data-testid=gallery-back]');
await page.waitForSelector('[data-testid=app-lock]');
check('coming back from the Gallery shows the blurred lock asking for the password', /blur/.test(await page.evaluate(() => getComputedStyle(document.querySelector('[data-testid=app-lock]')).backdropFilter || getComputedStyle(document.querySelector('[data-testid=app-lock]')).webkitBackdropFilter)));
await page.fill('[data-testid=lock-pass]', 'wrong'); await page.click('[data-testid=lock-submit]');
check('a wrong password keeps it locked', await page.locator('[data-testid=lock-error]').isVisible());
await page.fill('[data-testid=lock-pass]', '443262'); await page.click('[data-testid=lock-submit]');
await page.waitForSelector('[data-testid=app-lock]', { state: 'detached' });
check('the right password unlocks the app (Home)', await page.locator('[data-testid=home-page]').isVisible());
await browser.close();
console.log(`${pass}/${pass + fail} passed`);
process.exit(fail ? 1 : 0);
