import { chromium } from '../../desktop/node_modules/playwright/index.mjs';
import { launchUnlocked } from './launch.mjs';
const BASE = process.env.SPJ_WEB_URL || 'http://localhost:4173/';
let pass = 0, fail = 0;
const check = (n, ok, d = '') => { (ok ? pass++ : fail++); console.log(`${ok ? 'PASS' : 'FAIL'}  ${n}${ok ? '' : ' — ' + d}`); };
const browser = await launchUnlocked(chromium);
const page = await (await browser.newContext({ viewport: { width: 390, height: 844 } })).newPage();
await page.goto(BASE);
await page.waitForSelector('[data-testid=home-page]');
// photos in two categories: gold ring a (today, in stock), gold ring b (old, already sold), silver anklet c; d has no photo
await page.evaluate(async () => {
  const db = await new Promise((res, rej) => { const r = indexedDB.open('spj-photos', 1); r.onupgradeneeded = () => r.result.createObjectStore('photos'); r.onsuccess = () => res(r.result); r.onerror = () => rej(r.error); });
  const c = document.createElement('canvas'); c.width = 60; c.height = 60; c.getContext('2d').fillRect(0, 0, 60, 60);
  const blob = await new Promise((r) => c.toBlob(r, 'image/jpeg'));
  await new Promise((res) => { const t = db.transaction('photos', 'readwrite'); ['p1', 'p2', 'p3'].forEach((id) => t.objectStore('photos').put(blob, id)); t.oncomplete = res; });
  const p = (n) => String(n).padStart(2, '0'); const d = new Date(); const now = `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
  const mk = (id, type, metal, item, weight, photoId, date) => ({ id, date, type, metal, item, tunch: 92, weight, pcs: 1, note: '', photoId, createdAt: `${date}T10:00:00Z` });
  localStorage.setItem('spj.stock.v1', JSON.stringify([mk('a', 'in', 'gold', 'Gold Ring – Classic', 5.5, 'p1', now), mk('b', 'in', 'gold', 'Gold Ring – Classic', 6, 'p2', '2020-01-01'), mk('bo', 'out', 'gold', 'Gold Ring – Classic', 6, undefined, now), mk('c', 'in', 'silver', 'Silver Anklet – Traditional', 38.5, 'p3', now), mk('d', 'in', 'gold', 'Gold Chain – Daily Wear', 12.8, undefined, now)]));
});
await page.reload();
await page.waitForSelector('[data-testid=home-page]');
await page.click('[data-testid=open-gallery]');
await page.waitForSelector('[data-testid=gallery-page]');
const ls = (pg, key) => pg.evaluate((k) => JSON.parse(localStorage.getItem(k) || 'null'), key);
const n = () => page.locator('[data-testid=gallery-photo]').count();
check('opens on Gold, gold look, top switch Silver | Gold, All shows compact gold cards with only the item and its weight (no price, no + button, no pills)', (await page.getAttribute('[data-testid=gallery-page]', 'data-theme')) === 'gold' && (await page.locator('[data-testid=gallery-switch] button').allInnerTexts()).join('|') === 'Silver|Gold' && (await n()) === 2 && /^Gold Ring – Classic 5\.5 g$/.test((await page.locator('[data-testid=gallery-card]').first().innerText()).replace(/\s+/g, ' ').trim()));
{ const sw = await page.locator('[data-testid=gallery-switch]').boundingBox(); const vw = page.viewportSize().width; check('the Silver | Gold switch sits in the middle of the page', Math.abs((sw.x + sw.width / 2) - vw / 2) < 4 && sw.width < vw * 0.7, JSON.stringify(sw)); }
const themeColor = () => page.getAttribute('meta[name=theme-color]', 'content');
check('the status / address bar takes the gold page colour', (await themeColor()) === '#fffbf0', await themeColor());
check('bottom bar has only Fav, All and Albums', (await page.locator('[data-testid=gallery-nav] button').allInnerTexts()).join('|') === 'Fav|All|Albums');
await page.click('[data-testid=gallery-tab-albums]');
check('Albums: one album per category with its photo count', (await page.locator('[data-testid=gallery-album]').count()) === 1 && (await page.locator('[data-testid=gallery-album] .gx-count').innerText()) === '2');
await page.locator('[data-testid=gallery-album]').click();
check('opening an album shows its photos and a way back to Albums', (await n()) === 2 && (await page.locator('[data-testid=gallery-albums-back]').count()) === 1);
await page.click('[data-testid=gallery-albums-back]');
check('back to the albums list', (await page.locator('[data-testid=gallery-album]').count()) === 1);
await page.click('[data-testid=gallery-silver]');
check('Silver switch: silver look and only the silver photo / albums', (await page.getAttribute('[data-testid=gallery-page]', 'data-theme')) === 'silver' && (await page.locator('[data-testid=gallery-album]').count()) === 1 && (await page.locator('[data-testid=gallery-album]').innerText()).includes('Silver Anklet'));
check('Silver switches it to the silver colour', (await themeColor()) === '#fdfcff');
await page.click('[data-testid=gallery-gold]');
await page.click('[data-testid=gallery-tab-all]');
// customer picks: + on a photo, name window, Fav list per customer
await page.locator('[data-testid=gallery-heart]').nth(0).click();
check('+ on a photo opens a window asking the customer name; Add is off until a name is typed', await page.locator('[data-testid=like-window]').isVisible() && await page.locator('[data-testid=like-save]').isDisabled());
await page.fill('[data-testid=like-name]', 'Ramesh Kumar'); await page.click('[data-testid=like-save]');
await page.waitForSelector('[data-testid=like-window]', { state: 'detached' });
check('the heart turns gold once picked and a note confirms', (await page.locator('[data-testid=gallery-heart]').nth(0).getAttribute('class')).includes('liked') && (await page.locator('[data-testid=gallery-note]').innerText()).includes('Ramesh Kumar'));
check('the page says who it is choosing for', (await page.locator('[data-testid=gallery-current]').innerText()).includes('Ramesh Kumar'));
await page.locator('[data-testid=gallery-heart]').nth(1).click();
await page.waitForFunction(() => document.querySelectorAll('[data-testid=gallery-heart].liked').length === 2, null, { timeout: 3000 }).catch(() => {});
check('the next heart saves straight to the same customer, no window', (await page.locator('[data-testid=like-window]').count()) === 0 && (await page.locator('[data-testid=gallery-heart].liked').count()) === 2 && (await page.locator('[data-testid=gallery-note]').innerText()).includes('Ramesh Kumar'));
await page.locator('[data-testid=gallery-heart]').nth(1).click();
await page.waitForFunction(() => document.querySelectorAll('[data-testid=gallery-heart].liked').length === 1, null, { timeout: 3000 }).catch(() => {});
check('tapping a chosen heart again un-chooses it', (await page.locator('[data-testid=gallery-heart].liked').count()) === 1);
await page.locator('[data-testid=gallery-heart]').nth(1).click();
await page.waitForFunction(() => document.querySelectorAll('[data-testid=gallery-heart].liked').length === 2, null, { timeout: 3000 }).catch(() => {});
check('the header has a refresh button instead of a cart', (await page.locator('[data-testid=gallery-cart]').count()) === 0 && (await page.locator('[data-testid=gallery-refresh]').count()) === 1);
await page.click('[data-testid=gallery-refresh]');
check('refresh clears the chosen hearts and the customer', (await page.locator('[data-testid=gallery-heart].liked').count()) === 0 && (await page.locator('[data-testid=gallery-current]').count()) === 0);
await page.locator('[data-testid=gallery-heart]').nth(0).click();
check('after refresh the name is asked again, earlier customers offered', (await page.locator('[data-testid=like-known]').allInnerTexts()).join('|') === 'Ramesh Kumar');
await page.fill('[data-testid=like-name]', 'sunita devi'); await page.click('[data-testid=like-save]');
await page.waitForSelector('[data-testid=like-window]', { state: 'detached' });
await page.click('[data-testid=gallery-tab-fav]');
check('Fav lists every customer who has picked something, with their count', (await page.locator('[data-testid=gallery-customer]').count()) === 2 && (await page.locator('[data-testid=gallery-customers]').innerText()).replace(/\s+/g, ' ').includes('Ramesh Kumar 2'));
await page.locator('[data-testid=gallery-customer]').filter({ hasText: 'Ramesh' }).click();
check('tapping a customer shows all their selected photos (no heart there)', (await n()) === 2 && (await page.locator('[data-testid=gallery-heart]').count()) === 0 && (await page.locator('.gx-title small').innerText()).toLowerCase().includes('ramesh kumar'), JSON.stringify([await n(), await page.locator('[data-testid=gallery-heart]').count(), await page.locator('.gx-title small').innerText()]));
await page.click('[data-testid=gallery-customers-back]');
check('back to the customers list', (await page.locator('[data-testid=gallery-customer]').count()) === 2);
await page.reload(); await page.waitForSelector('[data-testid=home-page]'); await page.click('[data-testid=open-gallery]'); await page.click('[data-testid=gallery-tab-fav]');
check('picks are remembered after reopening', (await page.locator('[data-testid=gallery-customer]').count()) === 2);
await page.click('[data-testid=gallery-tab-all]');
// scrolling hides the bars, scrolling back up shows them
await page.evaluate(() => { const b = document.querySelector('[data-testid=gallery-body]'); const f = document.createElement('div'); f.style.height = '2000px'; b.appendChild(f); });
await page.evaluate(() => { document.querySelector('[data-testid=gallery-body]').scrollTop = 300; });
await page.waitForSelector('.gx.hide-bars', { timeout: 3000 }).catch(() => {});
check('scrolling down hides the header and the bottom bar', (await page.locator('.gx.hide-bars').count()) === 1);
await page.evaluate(() => { document.querySelector('[data-testid=gallery-body]').scrollTop = 120; });
await page.waitForFunction(() => !document.querySelector('.gx.hide-bars'), null, { timeout: 3000 }).catch(() => {});
check('scrolling back up brings them back', (await page.locator('.gx.hide-bars').count()) === 0);
await page.evaluate(() => { document.querySelector('[data-testid=gallery-body]').scrollTop = 0; });
await page.locator('[data-testid=gallery-photo]').first().click();
check('tapping a photo opens it on its own page (big, with its item and weight)', await page.locator('[data-testid=gallery-viewer]').isVisible() && (await page.locator('[data-testid=gallery-viewer] .gx-caption').innerText()).replace(/\s+/g, ' ').includes('5.5 g'));
await page.click('[data-testid=gallery-next]');
check('next shows the following piece', (await page.locator('[data-testid=gallery-viewer] .gx-caption').innerText()).replace(/\s+/g, ' ').includes('6 g'));
await page.click('[data-testid=gallery-viewer-back]');
await page.waitForSelector('[data-testid=gallery-viewer]', { state: 'detached' });
check('no lock while inside the Gallery', (await page.locator('[data-testid=app-lock]').count()) === 0);
await page.click('[data-testid=gallery-back]');
await page.waitForSelector('[data-testid=app-lock]');
check('leaving the Gallery restores the house maroon bars', (await themeColor()) === '#6b0f1a');
check('coming back from the Gallery shows the blurred lock asking for the password', /blur/.test(await page.evaluate(() => getComputedStyle(document.querySelector('[data-testid=app-lock]')).backdropFilter || getComputedStyle(document.querySelector('[data-testid=app-lock]')).webkitBackdropFilter)));
await page.click('[data-testid=lock-gallery]');
await page.waitForSelector('[data-testid=gallery-page]');
check('the lock offers a way back into the Gallery (no password needed)', (await page.locator('[data-testid=app-lock]').count()) === 0);
await page.click('[data-testid=gallery-back]');
await page.waitForSelector('[data-testid=app-lock]');
await page.fill('[data-testid=lock-pass]', 'wrong'); await page.click('[data-testid=lock-submit]');
check('a wrong password keeps it locked', await page.locator('[data-testid=lock-error]').isVisible());
await page.fill('[data-testid=lock-pass]', '443262'); await page.click('[data-testid=lock-submit]');
await page.waitForSelector('[data-testid=app-lock]', { state: 'detached' });
check('the right password unlocks the app (Home)', await page.locator('[data-testid=home-page]').isVisible());
// ---- press and hold to pick photos, delete them for good (password asked)
await page.click('[data-testid=open-gallery]'); await page.waitForSelector('[data-testid=gallery-page]');
const hold = async (loc) => { const b = await loc.boundingBox(); await page.mouse.move(b.x + b.width / 2, b.y + b.height / 2); await page.mouse.down(); await page.waitForTimeout(750); await page.mouse.up(); };
const goldBefore = await n();
await hold(page.locator('[data-testid=gallery-photo]').first());
check('press and hold starts picking: the bar shows 1 selected and the photo is not opened', (await page.locator('[data-testid=gallery-selected-count]').innerText()) === '1 selected' && (await page.locator('[data-testid=gallery-viewer]').count()) === 0);
await page.locator('[data-testid=gallery-photo]').nth(1).click();
check('tapping another photo adds it', (await page.locator('[data-testid=gallery-selected-count]').innerText()) === '2 selected');
await page.click('[data-testid=gallery-select-cancel]');
check('cancel leaves picking mode, nothing deleted', (await page.locator('[data-testid=gallery-select-bar]').count()) === 0 && (await n()) === goldBefore);
await hold(page.locator('[data-testid=gallery-photo]').first());
await page.locator('[data-testid=gallery-photo]').nth(1).click();
await page.click('[data-testid=gallery-delete]');
check('Delete asks for the password and warns it is for good', (await page.locator('[data-testid=delete-window]').innerText()).includes('2 photos forever'));
await page.fill('[data-testid=delete-pass]', 'wrong'); await page.click('[data-testid=delete-confirm]');
check('a wrong password deletes nothing', (await page.locator('[data-testid=delete-error]').count()) === 1 && (await ls(page, 'spj.stock.v1')).filter((e) => e.photoId).length === 3);
await page.fill('[data-testid=delete-pass]', '443262'); await page.click('[data-testid=delete-confirm]');
await page.waitForSelector('[data-testid=delete-window]', { state: 'detached' });
await page.waitForTimeout(400);
const stockNow = await ls(page, 'spj.stock.v1');
check('the right password deletes the photos: they leave the Gallery (no gold photo is left, so it shows Silver)', (await n()) === 1 && (await page.getAttribute('[data-testid=gallery-page]', 'data-theme')) === 'silver' && (await page.locator('[data-testid=gallery-select-bar]').count()) === 0, JSON.stringify([goldBefore, await n(), await page.locator('[data-testid=gallery-select-bar]').count()]));
check('the stock entries stay (weight, tunch...) but without a photo', stockNow.length === 5 && stockNow.filter((e) => e.photoId).length === 1 && stockNow.find((e) => e.id === 'a').weight === 5.5 && !!stockNow.find((e) => e.id === 'a').updatedAt);
check('the pictures are gone from the phone for good', await page.evaluate(async () => { const db = await new Promise((res, rej) => { const r = indexedDB.open('spj-photos', 1); r.onsuccess = () => res(r.result); r.onerror = () => rej(r.error); }); const get = (id) => new Promise((res) => { const q = db.transaction('photos').objectStore('photos').get(id); q.onsuccess = () => res(q.result); }); return !(await get('p1')) && !(await get('p2')) && !!(await get('p3')); }));
await browser.close();
console.log(`${pass}/${pass + fail} passed`);
process.exit(fail ? 1 : 0);
