import { chromium } from '../../desktop/node_modules/playwright/index.mjs';
const URL = process.env.URL ?? 'http://localhost:4173/';
let pass = 0, fail = 0;
const check = (n, ok, d = '') => { (ok ? pass++ : fail++); console.log(`${ok ? 'PASS' : 'FAIL'}  ${n}${ok ? '' : ' — ' + d}`); };
const browser = await chromium.launch({ channel: 'chromium' });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 } });
const page = await ctx.newPage();
await page.goto(URL);
check('the app opens on the sign-in screen', await page.locator('[data-testid=login-screen]').isVisible() && (await page.locator('[data-testid=home-page]').count()) === 0);
await page.fill('[data-testid=login-user]', 'SPJ'); await page.fill('[data-testid=login-pass]', 'wrong');
await page.click('[data-testid=login-submit]');
check('wrong password is refused', await page.locator('[data-testid=login-error]').isVisible());
await page.fill('[data-testid=login-user]', 'spj'); await page.fill('[data-testid=login-pass]', '443262');
await page.click('[data-testid=login-submit]');
await page.waitForSelector('[data-testid=home-page]');
check('SPJ / 443262 signs in', true);
await page.reload();
check('stays signed in while the app stays open', await page.locator('[data-testid=home-page]').isVisible());
await page.click('[data-testid=open-settings]');
await page.fill('[data-testid=pw-current]', '000000'); await page.fill('[data-testid=pw-new]', 'abcd1234'); await page.fill('[data-testid=pw-again]', 'abcd1234');
await page.click('[data-testid=pw-save]');
check('wrong current password is refused', (await page.textContent('[data-testid=pw-msg]')).includes('not correct'));
await page.fill('[data-testid=pw-current]', '443262');
await page.click('[data-testid=pw-save]');
check('password can be changed in Settings', (await page.textContent('[data-testid=pw-msg]')).includes('changed'));
const ctx2 = await browser.newContext({ storageState: await ctx.storageState() });
const p2 = await ctx2.newPage();
await p2.goto(URL);
check('a new visit asks again, and the new password works (the old one does not)', await p2.locator('[data-testid=login-screen]').isVisible());
await p2.fill('[data-testid=login-user]', 'SPJ'); await p2.fill('[data-testid=login-pass]', '443262'); await p2.click('[data-testid=login-submit]');
check('old password is refused', await p2.locator('[data-testid=login-error]').isVisible());
await p2.fill('[data-testid=login-pass]', 'abcd1234'); await p2.click('[data-testid=login-submit]');
await p2.waitForSelector('[data-testid=home-page]');
check('new password signs in', true);
await browser.close();
console.log(`${pass}/${pass + fail} passed`);
process.exit(fail ? 1 : 0);
