import { chromium } from '../../desktop/node_modules/playwright/index.mjs';
const URL = process.env.URL ?? 'http://localhost:4173/';
let pass = 0, fail = 0;
const check = (n, ok, d = '') => { (ok ? pass++ : fail++); console.log(`${ok ? 'PASS' : 'FAIL'}  ${n}${ok ? '' : ' — ' + d}`); };
const browser = await chromium.launch({ channel: 'chromium' });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 } });
const page = await ctx.newPage();
await page.goto(URL);
check('the app opens on the sign-in screen', await page.locator('[data-testid=login-screen]').isVisible() && (await page.locator('[data-testid=home-page]').count()) === 0);
await page.fill('[data-testid=login-user]', 'SPJ'); await page.fill('[data-testid=login-pass]', 'wrong');
await page.click('[data-testid=login-submit]');
check('wrong password is refused', await page.locator('[data-testid=login-error]').isVisible());
await page.fill('[data-testid=login-user]', 'spj'); await page.fill('[data-testid=login-pass]', '3262');
await page.click('[data-testid=login-submit]');
await page.waitForSelector('[data-testid=home-page]');
check('SPJ / 3262 signs in', true);
await page.reload();
check('stays signed in after a reload', await page.locator('[data-testid=home-page]').isVisible());
await page.click('[data-testid=open-settings]');
await page.fill('[data-testid=pw-current]', '000000'); await page.fill('[data-testid=pw-new]', 'abcd1234'); await page.fill('[data-testid=pw-again]', 'abcd1234');
await page.click('[data-testid=pw-save]');
check('wrong current password is refused', (await page.textContent('[data-testid=pw-msg]')).includes('not correct'));
await page.fill('[data-testid=pw-current]', '3262');
await page.click('[data-testid=pw-save]');
check('password can be changed in Settings', (await page.textContent('[data-testid=pw-msg]')).includes('changed'));
const st = await ctx.storageState();
const tab2 = await ctx.newPage(); await tab2.goto(URL);
check('a new tab on the same device is already signed in (login is remembered)', await tab2.locator('[data-testid=home-page]').isVisible());
await tab2.close();
st.origins.forEach((o) => { o.localStorage = o.localStorage.filter((i) => i.name !== 'spj.signedin.v1'); }); // as if signed out, user name still remembered
const ctx2 = await browser.newContext({ storageState: st });
const p2 = await ctx2.newPage();
await p2.goto(URL);
check('the sign-in screen remembers the user name', (await p2.inputValue('[data-testid=login-user]')) === 'SPJ');
await p2.fill('[data-testid=login-pass]', '3262'); await p2.click('[data-testid=login-submit]');
check('old password is refused', await p2.locator('[data-testid=login-error]').isVisible());
await p2.fill('[data-testid=login-pass]', 'abcd1234'); await p2.click('[data-testid=login-submit]');
await p2.waitForSelector('[data-testid=home-page]');
check('new password signs in', true);
await p2.reload();
check('and stays signed in after closing and reopening', await p2.locator('[data-testid=home-page]').isVisible());
// ---- the second shop: Kashi Jewellers (KJ / 0800), with its own data
const kctx = await browser.newContext({ viewport: { width: 390, height: 844 } });
const kp = await kctx.newPage();
await kp.goto(URL);
await kp.fill('[data-testid=login-user]', 'kj');
check('typing KJ shows Kashi Jewellers on the sign-in screen', (await kp.textContent('.login-card h1')).includes('KASHI JEWELLERS'));
await kp.fill('[data-testid=login-pass]', '3262'); await kp.click('[data-testid=login-submit]');
check('the SPJ password does not open KJ', await kp.locator('[data-testid=login-error]').isVisible());
await kp.fill('[data-testid=login-pass]', '0800'); await kp.click('[data-testid=login-submit]');
await kp.waitForSelector('[data-testid=home-page]');
check('KJ / 0800 signs in to Kashi Jewellers', (await kp.textContent('[data-testid=home-brand]')).includes('KASHI JEWELLERS'));
await kp.click('[data-testid=open-settings]');
check('Kashi Jewellers starts with its address and both owners', (await kp.inputValue('[data-testid=owner2-name]')) === 'Yogesh Soni' && (await kp.inputValue('[data-testid=owner2-phone]')) === '9929288743' && (await kp.locator('input[value="Main Bazar, Bhadra"]').count()) === 1 && (await kp.locator('input[value="Jaideep Soni"]').count()) === 1 && (await kp.locator('input[value="9782785300"]').count()) === 1);
check('it starts with no logo of S.P. Jewellers (a monogram instead)', (await kp.locator('[data-testid=logo-card] .home-logo.mono').count()) === 1);
// its data is kept apart: a cash entry saved as KJ is not in SPJ
await kp.evaluate(() => localStorage.setItem('kj.cash.v1', JSON.stringify([{ id: 'k1', date: '2026-10-01', type: 'in', amount: 5, note: 'KJ only', createdAt: '2026-10-01T10:00:00Z' }])));
check('KJ data lives under its own keys (the SPJ cash register is untouched)', (await kp.evaluate(() => localStorage.getItem('spj.cash.v1'))) === null);
await kp.click('[data-testid=sign-out]');
await kp.waitForSelector('[data-testid=login-screen]');
check('signing out returns to the sign-in screen', true);
await kp.fill('[data-testid=login-user]', 'SPJ'); await kp.fill('[data-testid=login-pass]', '3262'); await kp.click('[data-testid=login-submit]');
await kp.waitForSelector('[data-testid=home-page]');
check('then SPJ opens S.P. JEWELLERS with its own data', (await kp.textContent('[data-testid=home-brand]')).includes('S.P. JEWELLERS') && (await kp.evaluate(() => localStorage.getItem('spj.cash.v1'))) === null);
await browser.close();
console.log(`${pass}/${pass + fail} passed`);
process.exit(fail ? 1 : 0);
