import { chromium } from '../../desktop/node_modules/playwright/index.mjs';
import { launchUnlocked } from './launch.mjs';
const BASE = process.env.SPJ_WEB_URL || 'http://localhost:4173/';
let pass = 0, fail = 0;
const check = (n, ok, d = '') => { (ok ? pass++ : fail++); console.log(`${ok ? 'PASS' : 'FAIL'}  ${n}${ok ? '' : ' — ' + d}`); };
const browser = await launchUnlocked(chromium);
const page = await (await browser.newContext({ viewport: { width: 390, height: 844 } })).newPage();
await page.goto(BASE); await page.waitForSelector('[data-testid=home-page]');
// a saved bill of Rs 72,000 (10 g gold at 100 %, rate 72,000 per 10 g)
await page.evaluate(() => {
  const at = '2026-10-05T09:00:00.000Z';
  const bill = { id: 'bill1', number: 1, createdAt: at, updatedAt: at, customerName: 'Ramesh', customerPhone: '', customerLocality: '', pricing: { goldRate: 72000, goldRateUnit: 'per_10g', silverRate: 90000, silverRateUnit: 'per_10g', fineFormula: 'tunch_plus_wastage', gstEnabled: false, gstPercent: 3, roundGrandTotal: true }, items: [{ id: 'i1', description: 'Gold Ring – Classic', metal: 'gold', grossWt: 10, lessWt: 0, tunch: 100, wastage: 0, pcs: 1, labourRate: 0, labourMode: 'fixed', amountOverride: null }], otherCharges: [], printStatus: 'not_printed', printedAt: null, lastPrintError: null };
  localStorage.setItem('spj.history.v1', JSON.stringify([bill]));
});
await page.reload(); await page.waitForSelector('[data-testid=home-page]');
await page.click('[data-testid=tab-history]');
await page.getByRole('button', { name: 'View' }).first().click();
await page.waitForSelector('[data-testid=pay-bar]');
const flat = async (id) => (await page.textContent(`[data-testid=${id}]`)).replace(/\s/g, '');
check('the final bill shows Paid ₹0 and Left = the whole bill', (await flat('pay-paid')) === '₹0' && (await flat('pay-left')) === '₹72,000');
await page.click('[data-testid=pay-add]');
await page.waitForSelector('[data-testid=pay-window]');
check('the payment window shows the balance and today\'s day and date', (await flat('pay-window-left')) === '₹72,000' && /^(Mon|Tue|Wed|Thu|Fri|Sat|Sun),/.test((await page.textContent('[data-testid=pay-when]')).trim()));
await page.click('[data-testid=pay-save]');
check('an empty amount is refused', (await page.textContent('[data-testid=pay-error]')).includes('Enter the amount'));
await page.fill('[data-testid=pay-amount]', '80000'); await page.waitForTimeout(150); await page.click('[data-testid=pay-save]');
check('more than the balance is refused', (await page.textContent('[data-testid=pay-error]')).includes('72,000'));
await page.fill('[data-testid=pay-amount]', '20000'); await page.waitForTimeout(150); await page.click('[data-testid=pay-save]');
await page.waitForSelector('[data-testid=pay-window]', { state: 'detached' });
await page.waitForFunction(() => document.querySelector('[data-testid=pay-left]')?.textContent.replace(/\s/g, '') === '₹52,000');
check('after ₹20,000: Paid ₹20,000, Left ₹52,000', (await flat('pay-paid')) === '₹20,000' && (await flat('pay-left')) === '₹52,000');
const frame = page.frameLocator('[data-testid=preview-frame]');
await frame.locator('body').waitFor();
await page.waitForTimeout(300);
const body = await frame.locator('body').innerText();
check('the bill itself lists the payment (Cash) with day and date, and the balance', /Paid ·\s*Cash ·\s*(Mon|Tue|Wed|Thu|Fri|Sat|Sun),/.test(body) && /BALANCE/.test(body) && body.includes('52,000'), body.slice(-300));
await page.click('[data-testid=pay-add]'); await page.fill('[data-testid=pay-amount]', '12000'); await page.waitForTimeout(150); await page.click('[data-testid=pay-save]');
await page.waitForFunction(() => document.querySelector('[data-testid=pay-left]')?.textContent.replace(/\s/g, '') === '₹40,000');
check('a second payment adds on: Paid ₹32,000, Left ₹40,000', (await flat('pay-paid')) === '₹32,000' && (await flat('pay-left')) === '₹40,000');
check('earlier payments have no edit or delete controls', (await page.locator('[data-testid=pay-window]').count()) === 0 && (await page.getByRole('button', { name: /edit|delete|remove/i }).count()) === 0);
await page.click('[data-testid=mark-clear]');
check('Clear warns that money is still left', (await page.locator('.sheet').innerText()).includes('40,000'));
await page.locator('.sheet').getByRole('button', { name: 'Yes, Clear' }).click();
await page.waitForSelector('[data-testid=preview-screen]', { state: 'detached' });
await page.click('[data-testid=tab-history]');
check('History shows Paid and Left on the card', (await page.locator('[data-testid=hist-pay]').innerText()).replace(/\s/g, '').includes('Left₹40,000'));
await page.locator('[data-testid=hist-top]').first().click();
await page.waitForSelector('[data-testid=pay-bar]');
check('after Clear nothing more can be added', (await page.locator('[data-testid=pay-add]').count()) === 0 && (await flat('pay-paid')) === '₹32,000');
// ---- the deposit card while making a bill
await page.getByLabel('Close preview').click();
await page.click('[data-testid=fab-new]'); await page.waitForSelector('[data-testid=estimate-page]');
await page.click('[data-testid=add-item]'); await page.waitForSelector('[data-testid=picker-modal]');
await page.locator('[data-testid=pick-option]').filter({ hasText: 'Gold Ring' }).click();
await page.waitForSelector('[data-testid=picker-modal]', { state: 'detached' });
const card = page.locator('[data-testid=item-card]').first();
await card.getByRole('button', { name: 'Gold', exact: true }).click();
await card.locator('[data-testid=gross]').fill('10');
await card.locator('[data-testid=karat]').fill('24');
await page.waitForFunction(() => document.querySelector('[data-testid=dep-total]')?.textContent.replace(/\s/g, '') === '₹72,000', null, { timeout: 4000 }).catch(() => {});
check('the bill page has a Payment card with the total and what is left', (await flat('dep-total')) === '₹72,000' && (await flat('dep-left')) === '₹72,000');
await page.fill('[data-testid=deposit]', '20000');
await page.waitForFunction(() => document.querySelector('[data-testid=dep-left]')?.textContent.replace(/\s/g, '') === '₹52,000', null, { timeout: 3000 }).catch(() => {});
check('typing the amount deposited shows what is left (₹52,000)', (await flat('dep-left')) === '₹52,000');
await page.fill('[data-testid=deposit]', '90000'); await page.waitForTimeout(200);
await page.click('[data-testid=save]');
check('a deposit above the bill total is refused', (await page.locator('[data-testid=issues]').count()) === 1 && (await page.locator('[data-testid=issues]').innerText()).includes('more than the bill total'));
await page.getByRole('button', { name: 'OK' }).click();
await page.fill('[data-testid=deposit]', '20000'); await page.waitForTimeout(250);
await page.click('[data-testid=save]');
await page.waitForSelector('[data-testid=pay-bar]');
await page.waitForFunction(() => document.querySelector('[data-testid=pay-left]')?.textContent.replace(/\s/g, '') === '₹52,000', null, { timeout: 3000 }).catch(() => {});
check('after Save the deposit is the first payment: Paid ₹20,000, Left ₹52,000', (await flat('pay-paid')) === '₹20,000' && (await flat('pay-left')) === '₹52,000');
const f2 = page.frameLocator('[data-testid=preview-frame]');
await f2.locator('body').waitFor(); await page.waitForTimeout(300);
const t2 = await f2.locator('body').innerText();
check('the saved bill lists that payment with its day and date, and the balance', /Paid ·\s*(Mon|Tue|Wed|Thu|Fri|Sat|Sun),/.test(t2) && /BALANCE/.test(t2), t2.slice(-200));
// ---- submitted gold / silver on the bill page: its weight is cut and the bill is made on the net weight (same karat as bought)
await page.getByLabel('Close preview').click();
await page.click('[data-testid=tab-history]').catch(() => {});
await page.click('[data-testid=fab-new]'); await page.waitForSelector('[data-testid=estimate-page]');
await page.click('[data-testid=add-item]'); await page.waitForSelector('[data-testid=picker-modal]');
await page.locator('[data-testid=pick-option]').filter({ hasText: 'Gold Ring' }).click();
await page.waitForSelector('[data-testid=picker-modal]', { state: 'detached' });
const c2 = page.locator('[data-testid=item-card]').first();
await c2.getByRole('button', { name: 'Gold', exact: true }).click();
await c2.locator('[data-testid=gross]').fill('10');
await c2.locator('[data-testid=karat]').fill('24');
await page.waitForFunction(() => document.querySelector('[data-testid=dep-total]')?.textContent.replace(/\s/g, '') === '₹72,000', null, { timeout: 4000 }).catch(() => {});
check('the Payment card has Submitted gold and Submitted silver (grams)', await page.locator('[data-testid=submitted-gold]').isVisible() && await page.locator('[data-testid=submitted-silver]').isVisible());
check('the submitted gold has a rate box that starts at the bill\'s 24K rate (72000 per 10 g)', (await page.inputValue('[data-testid=submitted-gold-rate]')) === '72000');
await page.fill('[data-testid=submitted-gold]', '4'); await page.waitForTimeout(300);
await page.waitForFunction(() => document.querySelector('[data-testid=credit-gold]'), null, { timeout: 3000 }).catch(() => {});
check('4 g at the 24K rate (100 %, 7,200 a gram) is cut from the bill: −₹28,800', (await flat('credit-gold')) === '−₹28,800', await flat('credit-gold'));
await page.waitForFunction(() => document.querySelector('[data-testid=dep-total]')?.textContent.replace(/\s/g, '') === '₹43,200', null, { timeout: 3000 }).catch(() => {});
check('the bill total falls to ₹43,200', (await flat('dep-total')) === '₹43,200', await flat('dep-total'));
await page.fill('[data-testid=submitted-gold-rate]', '75000'); await page.waitForTimeout(300);
await page.waitForFunction(() => document.querySelector('[data-testid=credit-gold]')?.textContent.replace(/\s/g, '') === '−₹30,000', null, { timeout: 3000 }).catch(() => {});
check('a rate typed for the submitted gold (75,000) changes only that: −₹30,000, total ₹42,000', (await flat('credit-gold')) === '−₹30,000' && (await flat('dep-total')) === '₹42,000', `${await flat('credit-gold')} ${await flat('dep-total')}`);
check('the gold bought on the bill is still priced at the bill\'s own rate (item amount ₹72,000)', (await c2.locator('[data-testid=amount]').innerText()).replace(/\s/g, '') === '₹72,000', await c2.locator('[data-testid=amount]').innerText());
await page.fill('[data-testid=deposit]', '10000'); await page.waitForTimeout(300);
check('cash deposited counts on the lower total: Left ₹32,000', (await flat('dep-left')) === '₹32,000', await flat('dep-left'));
await page.fill('[data-testid=submitted-gold]', '12'); await page.waitForTimeout(250);
await page.click('[data-testid=save]');
check('submitting more gold than was bought is refused', (await page.locator('[data-testid=issues]').count()) === 1 && (await page.locator('[data-testid=issues]').innerText()).includes('more than the gold'));
await page.getByRole('button', { name: 'OK' }).click();
await page.fill('[data-testid=submitted-gold]', '4'); await page.waitForTimeout(300);
await page.click('[data-testid=save]');
await page.waitForSelector('[data-testid=pay-bar]');
await page.waitForFunction(() => document.querySelector('[data-testid=pay-left]')?.textContent.replace(/\s/g, '') === '₹32,000', null, { timeout: 3000 }).catch(() => {});
check('saved: Paid ₹10,000 (cash only; the submitted gold is not a payment), Left ₹32,000', (await flat('pay-paid')) === '₹10,000' && (await flat('pay-left')) === '₹32,000', `${await flat('pay-paid')} ${await flat('pay-left')}`);
await page.waitForTimeout(500);
const savedText = await page.frameLocator('[data-testid=preview-frame]').locator('body').innerText();
check('the bill has one simple row "Submitted 4 g gold @ ₹75,000 / 10 g" with −₹30,000, then TOTAL ₹42,000 (no karat, no Net Wt. rows)', /Submitted 4 g gold @ ₹75,000 \/ 10 g\s*−₹30,000/.test(savedText) && /TOTAL\s*₹42,000/.test(savedText) && !/Net Gold Wt|22K|24K/.test(savedText), savedText.slice(-600));

// ---- later on: gold submitted after the bill is added as a payment with that day's price
await page.click('[data-testid=pay-add]'); await page.waitForSelector('[data-testid=pay-window]');
await page.click('[data-testid=pay-mode-gold]');
check('later, Gold asks only for the weight and a rate for that one (no karat, no cut)', (await page.locator('[data-testid=pay-gold-wt], [data-testid=pay-gold-rate]').count()) === 2 && (await page.locator('[data-testid=pay-gold-karat], [data-testid=pay-gold-cut]').count()) === 0 && (await page.inputValue('[data-testid=pay-gold-rate]')) === '72000');
await page.fill('[data-testid=pay-gold-wt]', '2'); await page.fill('[data-testid=pay-gold-rate]', '75000'); await page.waitForTimeout(300);
await page.waitForFunction(() => document.querySelector('[data-testid=pay-gold-value]')?.textContent.replace(/\s/g, '') === '₹15,000', null, { timeout: 3000 }).catch(() => {});
check('2 g at that day\'s price 75,000 per 10 g, 24K (100 %) = ₹15,000', (await flat('pay-gold-value')) === '₹15,000', await flat('pay-gold-value'));
await page.click('[data-testid=pay-save]');
await page.waitForSelector('[data-testid=pay-window]', { state: 'detached' });
await page.waitForFunction(() => document.querySelector('[data-testid=pay-left]')?.textContent.replace(/\s/g, '') === '₹17,000', null, { timeout: 3000 }).catch(() => {});
check('it is cut from the balance: Left ₹17,000', (await flat('pay-left')) === '₹17,000', await flat('pay-left'));
await page.waitForTimeout(400);
const laterText = await page.frameLocator('[data-testid=preview-frame]').locator('body').innerText();
check('the bill lists "Submitted gold 2 g" as a payment with its date', /Paid ·\s*Submitted gold 2 g ·\s*(Mon|Tue|Wed|Thu|Fri|Sat|Sun),/.test(laterText), laterText.slice(-400));
await browser.close();
console.log(`${pass}/${pass + fail} passed`);
process.exit(fail ? 1 : 0);
