import { chromium } from '../../desktop/node_modules/playwright/index.mjs';
import { launchUnlocked } from './launch.mjs';
const BASE = process.env.SPJ_WEB_URL || 'http://localhost:4173/';
let pass = 0, fail = 0;
const check = (n, ok, d = '') => { (ok ? pass++ : fail++); console.log(`${ok ? 'PASS' : 'FAIL'}  ${n}${ok ? '' : ' — ' + d}`); };
const browser = await launchUnlocked(chromium);
const page = await (await browser.newContext({ viewport: { width: 390, height: 844 } })).newPage();
await page.goto(BASE); await page.waitForSelector('[data-testid=home-page]');
// a saved bill of Rs 72,000 (10 g gold at 100 %, rate 72,000 per 10 g)
await page.evaluate(() => {
  const at = '2026-10-05T09:00:00.000Z';
  const bill = { id: 'bill1', number: 1, createdAt: at, updatedAt: at, customerName: 'Ramesh', customerPhone: '', customerLocality: '', pricing: { goldRate: 72000, goldRateUnit: 'per_10g', silverRate: 90000, silverRateUnit: 'per_10g', fineFormula: 'tunch_plus_wastage', gstEnabled: false, gstPercent: 3, roundGrandTotal: true }, items: [{ id: 'i1', description: 'Gold Ring – Classic', metal: 'gold', grossWt: 10, lessWt: 0, tunch: 100, wastage: 0, pcs: 1, labourRate: 0, labourMode: 'fixed', amountOverride: null }], otherCharges: [], printStatus: 'not_printed', printedAt: null, lastPrintError: null };
  localStorage.setItem('spj.history.v1', JSON.stringify([bill]));
});
await page.reload(); await page.waitForSelector('[data-testid=home-page]');
await page.click('[data-testid=tab-history]');
await page.getByRole('button', { name: 'View' }).first().click();
await page.waitForSelector('[data-testid=pay-bar]');
const flat = async (id) => (await page.textContent(`[data-testid=${id}]`)).replace(/\s/g, '');
check('the final bill shows Paid ₹0 and Left = the whole bill', (await flat('pay-paid')) === '₹0' && (await flat('pay-left')) === '₹72,000');
await page.click('[data-testid=pay-add]');
await page.waitForSelector('[data-testid=pay-window]');
check('the payment window shows the balance and today\'s day and date', (await flat('pay-window-left')) === '₹72,000' && /^(Mon|Tue|Wed|Thu|Fri|Sat|Sun),/.test((await page.textContent('[data-testid=pay-when]')).trim()));
await page.click('[data-testid=pay-save]');
check('an empty amount is refused', (await page.textContent('[data-testid=pay-error]')).includes('Enter the amount'));
await page.fill('[data-testid=pay-amount]', '80000'); await page.waitForTimeout(150); await page.click('[data-testid=pay-save]');
check('more than the balance is refused', (await page.textContent('[data-testid=pay-error]')).includes('72,000'));
await page.fill('[data-testid=pay-amount]', '20000'); await page.waitForTimeout(150); await page.click('[data-testid=pay-save]');
await page.waitForSelector('[data-testid=pay-window]', { state: 'detached' });
await page.waitForFunction(() => document.querySelector('[data-testid=pay-left]')?.textContent.replace(/\s/g, '') === '₹52,000');
check('after ₹20,000: Paid ₹20,000, Left ₹52,000', (await flat('pay-paid')) === '₹20,000' && (await flat('pay-left')) === '₹52,000');
const frame = page.frameLocator('[data-testid=preview-frame]');
await frame.locator('body').waitFor();
await page.waitForTimeout(300);
const body = await frame.locator('body').innerText();
check('the bill itself lists the payment with day and date, and the balance', /Paid ·\s*(Mon|Tue|Wed|Thu|Fri|Sat|Sun),/.test(body) && /BALANCE/.test(body) && body.includes('52,000'), body.slice(-300));
await page.click('[data-testid=pay-add]'); await page.fill('[data-testid=pay-amount]', '12000'); await page.waitForTimeout(150); await page.click('[data-testid=pay-save]');
await page.waitForFunction(() => document.querySelector('[data-testid=pay-left]')?.textContent.replace(/\s/g, '') === '₹40,000');
check('a second payment adds on: Paid ₹32,000, Left ₹40,000', (await flat('pay-paid')) === '₹32,000' && (await flat('pay-left')) === '₹40,000');
check('earlier payments have no edit or delete controls', (await page.locator('[data-testid=pay-window]').count()) === 0 && (await page.getByRole('button', { name: /edit|delete|remove/i }).count()) === 0);
await page.click('[data-testid=mark-clear]');
check('Clear warns that money is still left', (await page.locator('.sheet').innerText()).includes('40,000'));
await page.locator('.sheet').getByRole('button', { name: 'Yes, Clear' }).click();
await page.waitForSelector('[data-testid=preview-screen]', { state: 'detached' });
await page.click('[data-testid=tab-history]');
check('History shows Paid and Left on the card', (await page.locator('[data-testid=hist-pay]').innerText()).replace(/\s/g, '').includes('Left₹40,000'));
await page.locator('[data-testid=hist-top]').first().click();
await page.waitForSelector('[data-testid=pay-bar]');
check('after Clear nothing more can be added', (await page.locator('[data-testid=pay-add]').count()) === 0 && (await flat('pay-paid')) === '₹32,000');
// ---- the deposit card while making a bill
await page.getByLabel('Close preview').click();
await page.click('[data-testid=fab-new]'); await page.waitForSelector('[data-testid=estimate-page]');
await page.click('[data-testid=add-item]'); await page.waitForSelector('[data-testid=picker-modal]');
await page.locator('[data-testid=pick-option]').filter({ hasText: 'Gold Ring' }).click();
await page.waitForSelector('[data-testid=picker-modal]', { state: 'detached' });
const card = page.locator('[data-testid=item-card]').first();
await card.getByRole('button', { name: 'Gold', exact: true }).click();
await card.locator('[data-testid=gross]').fill('10');
await card.locator('[data-testid=karat]').fill('24');
await page.waitForFunction(() => document.querySelector('[data-testid=dep-total]')?.textContent.replace(/\s/g, '') === '₹72,000', null, { timeout: 4000 }).catch(() => {});
check('the bill page has a Payment card with the total and what is left', (await flat('dep-total')) === '₹72,000' && (await flat('dep-left')) === '₹72,000');
await page.fill('[data-testid=deposit]', '20000');
await page.waitForFunction(() => document.querySelector('[data-testid=dep-left]')?.textContent.replace(/\s/g, '') === '₹52,000', null, { timeout: 3000 }).catch(() => {});
check('typing the amount deposited shows what is left (₹52,000)', (await flat('dep-left')) === '₹52,000');
await page.fill('[data-testid=deposit]', '90000'); await page.waitForTimeout(200);
await page.click('[data-testid=save]');
check('a deposit above the bill total is refused', (await page.locator('[data-testid=issues]').count()) === 1 && (await page.locator('[data-testid=issues]').innerText()).includes('more than the bill total'));
await page.getByRole('button', { name: 'OK' }).click();
await page.fill('[data-testid=deposit]', '20000'); await page.waitForTimeout(250);
await page.click('[data-testid=save]');
await page.waitForSelector('[data-testid=pay-bar]');
await page.waitForFunction(() => document.querySelector('[data-testid=pay-left]')?.textContent.replace(/\s/g, '') === '₹52,000', null, { timeout: 3000 }).catch(() => {});
check('after Save the deposit is the first payment: Paid ₹20,000, Left ₹52,000', (await flat('pay-paid')) === '₹20,000' && (await flat('pay-left')) === '₹52,000');
const f2 = page.frameLocator('[data-testid=preview-frame]');
await f2.locator('body').waitFor(); await page.waitForTimeout(300);
const t2 = await f2.locator('body').innerText();
check('the saved bill lists that payment with its day and date, and the balance', /Paid ·\s*(Mon|Tue|Wed|Thu|Fri|Sat|Sun),/.test(t2) && /BALANCE/.test(t2), t2.slice(-200));
await browser.close();
console.log(`${pass}/${pass + fail} passed`);
process.exit(fail ? 1 : 0);
